WBS/Controllers/AdministratorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Text;

namespace WBS.Controllers
{
    public class AdministratorController : Controller
    {
        // GET: Administrator
        public ActionResult Index(int pageindex=1,int pagesize=5,string Name="")
        {
          
            if (string.IsNullOrEmpty(Name))
            {
                Name = "";
            }
          List<WBSModel.Tb_GoodsInfo> list=  WBSBLL.GoodsInfoBll.GoodsInfoShow(pageindex, pagesize, Name, out int Count);
            int pagecount = Count; //(list == null || list.Count == 0) ? 0 : list[0].Rows;//总页数
            int z = (int)Math.Ceiling((decimal)pagecount / pagesize);
            ViewBag.PagePro = pageindex <= 1 ? 1 : pageindex - 1;
            ViewBag.PageNext = pageindex >= z ? z : pageindex + 1;
            ViewBag.PageList = z;
            return View(list);
        }


        public  ActionResult Login()
        {

            return View();
        }
       



        [HttpGet]
        public void DengLu(string Phone)
        {
            //HttpCookie cookie = Request.Cookies["Cooks"];
            //if (cookie==null)
            //{
            //     cookie = new HttpCookie("Cooks");
            //}
            string code = "123456";//WBSDAL.PhoneCode.Code(Phone);
            Session["code"] = code;
            //cookie.Value = code;
            //cookie.Expires = DateTime.Now.AddMinutes(5);
            //Response.Cookies.Add(cookie);
            //return Json(code);
        }

        [HttpPost]
        public void Login(string phone, string pnum)
        {
            //HttpCookie cookie = Request.Cookies["Cooks"];
            //string Code =cookie.Value;
          string c=  Session["code"].ToString();
            if (pnum==c)
            {
                Response.Write("<script>alert('登录成功');location.href='/Administrator/Index';</script>");
            }
        }
    }
}

WBS/Controllers/GoodsInfoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WBS.Controllers
{
    public class GoodsInfoController : Controller
    {
        // GET: GoodsInfo
        public ActionResult Index()
        {
            return View();
        }

    }
}

WBS/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WBS.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

WBS/Controllers/HtddController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net.Http;
using System.IO;
using WBSModel;
using Newtonsoft.Json;

namespace WBS.Controllers
{
    public class HtddController : Controller
    {
        // GET: Htdd
        #region 后台订单显示
        public ActionResult Show()
        {
            string url="";
            HttpClient  http = new HttpClient();
            HttpResponseMessage message = http.GetAsync(url).Result;
            string sql = message.Content.ReadAsStringAsync().Result;
            List<Tb_OrderInfo> list = JsonConvert.DeserializeObject<List<Tb_OrderInfo>>(sql);
            return View(list);
        }
        #endregion
        #region 订单明细
        public ActionResult MxShow()
        {
            string url = "";
            HttpClient http = new HttpClient();
            HttpResponseMessage message = http.GetAsync(url).Result;
            string sql = message.Content.ReadAsStringAsync().Result;
            List<Tb_SaleNum> list = JsonConvert.DeserializeObject<List<Tb_SaleNum>>(sql);
            return View(list);
        }
        #endregion
    }
}

WBS/Views/Administrator/Index.cshtml
@model List<WBSModel.Tb_GoodsInfo>
@{
    ViewBag.Title = "Index";
}
<script src="~/layui/layui.js"></script>
@*<link href="~/layui/css/layui.css" rel="stylesheet" />*@
<table class="table-bordered table" style="text-align:center">
    <thead style="background-color:aquamarine">
        <tr>
            <td>商品名称</td>
            <td>是否显示</td>
            <td>价格</td>
            <td>重量</td>
            <td>详情</td>
            <td>状态</td>
            <td>浏览量</td>
            <td>销售量</td>
            <td>评价数量</td>
            <td>类型</td>
            <td>是否包邮</td>
            <td>操作</td>
        </tr>
    </thead>
    <tbody>
        @foreach (var s in Model)
        {
            <tr>
                <td>@s.GoodsName</td>
                <td>@(s.GoodsDisplay == 0 ? "显示" : "No")</td>
                <td>@s.GoodsPrice</td>
                <td>@s.GoodsWeight</td>
                <td>@s.GoodsRemark</td>
                <td>@s.GoodsState</td>
                <td>@s.GoodsBorwseNum</td>
                <td>@s.GoodsSaleNum</td>
                <td>@s.GoodsEvaluaNum</td>
                <td>@s.CommodTypeID</td>
                <td>@s.GoodsFreight</td>
                <td>
                    @Html.ActionLink("修改", null)
                    @Html.ActionLink("删除", null)
                </td>
            </tr>
        }
    </tbody>
</table>

<a href="/Index/index/?pageindex=1">首页</a>
<a href="/Index/index/?pageindex=@ViewBag.PagePro">上一页</a>
<a href="/Index/index/?pageindex=@ViewBag.PageNext">下一页</a>
<a href="/Index/index/?pageindex=@ViewBag.PageList">尾页</a>

WBS/Views/Administrator/Login.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
    <link rel="stylesheet" type="text/css" href="~/static/css/main.css">
    <link rel="stylesheet" type="text/css" href="~/layui/css/layui.css">
    <script type="text/javascript" src="~/layui/layui.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <link id="layuicss-layer" rel="stylesheet" href="http://demo.cssmoban.com/cssthemes5/ccpt_5_bbh/res/layui/css/modules/layer/default/layer.css?v=3.1.1" media="all">
</head>
<body>


    <div class="site-nav-bg">
        <div class="site-nav w1200">
            <p class="sn-back-home">
                <i class="layui-icon layui-icon-home"></i>
                <a href="#">首页</a>
            </p>
            <div class="sn-quick-menu">
                <div class="login"><a href="login.html">登录</a></div>
                <div class="sp-cart"><a href="shopcart.html">购物车</a><span>2</span></div>
            </div>
        </div>
    </div>



    <div class="header">
        <div class="headerLayout w1200">
            <div class="headerCon">
                <h1 class="mallLogo">
                    <a href="#" title="yy商城">
                        <img src="../res/static/img/logo.png">
                    </a>
                </h1>
                <div class="mallSearch">
                    <form action="" class="layui-form" novalidate="">
                        <input type="text" name="title" required="" lay-verify="required" autocomplete="off" xdclass="layui-input" placeholder="请输入需要的商品">




                        <button class="layui-btn" lay-submit="" lay-filter="formDemo">
                            <i class="layui-icon layui-icon-search"></i>
                        </button>
                        <input type="hidden" name="" value="">
                    </form>
                </div>
            </div>
        </div>
    </div>


    <div class="content content-nav-base  login-content">
        <div class="main-nav">
            <div class="inner-cont0">
                <div class="inner-cont1 w1200">
                    <div class="inner-cont2">
                        <a href="commodity.html" class="active">所有商品</a>
                        <a href="buytoday.html">今日团购</a>
                        <a href="information.html">yy资讯</a>
                        <a href="about.html">关于我们</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="login-bg">
            <div class="login-cont w1200">
                <div class="form-box">
                    @using (Html.BeginForm("Login", "Administrator", FormMethod.Post, new { @enctype = "multipart/form-data" }))
                    {

                    <form class="layui-form" action="/Administrator/Login">
                        <legend>手机号登录</legend>
                        <div class="layui-form-item">
                            <div class="layui-inline iphone">
                                <div class="layui-input-inline">
                                    <i class="layui-icon layui-icon-cellphone iphone-icon"></i>
                                    <input type="tel" name="phone" id="phone" lay-verify="required|phone" placeholder="请输入手机号" autocomplete="off" class="layui-input">
                                </div>
                            </div>
                            <div class="layui-inline veri-code">
                                <div class="layui-input-inline">
                                    <input id="pnum" type="text" name="pnum" lay-verify="required" placeholder="请输入验证码" autocomplete="off" class="layui-input">
                                    <input type="button" class="layui-btn" id="find" value="验证码">
                                </div>
                            </div>
                        </div>
                        <div class="layui-form-item login-btn">
                            <div class="layui-input-block"><input id="Submit1" class="layui-btn" type="submit" value="后台代码登录" />
                                @*<button class="layui-btn" lay-submit="" lay-filter="demo1" onclick="return false">登录</button>*@
                            </div>
                            
                        </div>
                    </form>
                    }
                </div>
            </div>
        </div>
    </div>

    <div class="footer">
        <div class="ng-promise-box">
            <div class="ng-promise w1200">
                <p class="text">
                    <a class="icon1" href="javascript:;">7天无理由退换货</a>
                    <a class="icon2" href="javascript:;">满99元全场免邮</a>
                    <a class="icon3" style="margin-right: 0" href="javascript:;">100%品质保证</a>
                </p>
            </div>
        </div>
        <div class="mod_help w1200">
            <p>
                <a href="javascript:;">关于我们</a>
                <span>|</span>
                <a href="javascript:;">帮助中心</a>
                <span>|</span>
                <a href="javascript:;">售后服务</a>
                <span>|</span>
                <a href="javascript:;">yy资讯</a>
                <span>|</span>
                <a href="javascript:;">关于货源</a>
            </p>
            <p class="coty">yy商城版权所有 © 2019-2020</p>
        </div>
    </div>
    <script type="text/javascript">
        layui.config({
            base: '../res/static/js/util' //你存放新模块的目录，注意，不是layui的模块目录
        }).use(['jquery', 'form'], function () {
            var $ = layui.$, form = layui.form;


            $("#find").click(function () {
                //if (!/^1\d{10}$/.test($("#phone").val())) {
                //    layer.msg("请输入正确的手机号");
                //    return false;
                //}
                


                    $.ajax({
                        type: "get",
                        url: "/Administrator/DengLu?Phone=" + $("#phone").val(),
                        dataType: "json",//返回的

                        success: function (data) {
                            console.log('right:'+data);
                            if (data.result) {
                                $("#find").addClass(" layui-btn-disabled");
                                $('#find').attr('disabled', "true");
                                settime(this);

                                $("#msg").text(data.msg);
                            } else {
                                layer.msg(data.msg);
                            }
                        },
                        error: function (msg) {
                            console.log('erro:'+msg);
                        }
                    });
                
                })
        
            });
        
            var countdown = 60;
            function settime(obj) {
                if (countdown == 0) {
                    obj.removeAttribute("disabled");
                    obj.classList.remove("layui-btn-disabled")
                    obj.value = "获取验证码";
                    countdown = 60;
                    return;
                } else {
                    obj.setAttribute("disabled", true);
                    obj.value = "重新发送(" + countdown + ")";
                    countdown--;

                    setTimeout(function () {
                        settime(obj)
                    }
                        , 1000)
                }
            }
       

        document.getElementById("find").onclick = function () { settime(this); }



    </script>


</body>
</html>

WBS/Views/Htdd/Show.cshtml
@{
    ViewBag.Title = "Show";
}
@using WBSModel;
@model List<Tb_OrderInfo>
<h2>Show</h2>
<table>
    <tr>
        <td>订单号</td>
        <td>下单日期</td>
        <td>客户ID</td>
        <td>订单状态</td>
        <td>收获人表</td>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.OrderInfoID</td>
            <td>@item.OrderInfoTime</td>
            <td>@item.MemberID</td>
            <td>@item.OrderInfoStat</td>
            <td>@item.ConsigneeID</td>
            <td>@Html.ActionLink("详情","")</td>
        </tr>
    }
</table>

WBS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - 我的 ASP.NET 应用程序</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @*<div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("应用程序名称", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("主页", "Index", "Home")</li>
                    <li>@Html.ActionLink("关于", "About", "Home")</li>
                    <li>@Html.ActionLink("联系方式", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>*@
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - 我的 ASP.NET 应用程序</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>